schema_version = "1.0.0"

id = "ice_cube_rig"
version = "2.0.10"
name = "Ice Cube Rig"
tagline = "UI and backend addon for the Minecraft Ice Cube Rig!"
maintainer = "DarthLilo"

type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Local skin and preset management"